This closes #83 adding commit info in the version of Apia
asr/apia pull request #86
Opened 2017-01-17 15:25 UTC by jonaprieto

2017-01-17 22:41 UTC, asr requested changes
Good job!

Please fix the test-suite and the HLint warnings in `Setup.hs`.

2017-01-18 12:46 UTC, asr commented
The test-suite continues failing...

2017-01-18 13:16 UTC, asr commented on Setup.hs
> +{-# OPTIONS_GHC -fno-warn-deprecations #-}
According to the GHC documentation (various versions) this flag is called `warnings-deprecations` so you should use `-fno-warn-warnings-deprecations`. In fact, the synonymous name `deprecations` is not documented, and GHC shouldn't report something like

```
dist/setup/setup.hs:56:37: warning: [-Wdeprecations]
 ```

but

```
dist/setup/setup.hs:56:37: warning: [-Wwarnings-deprecations]
 ```

Please create a MVE a file an GHC issue.

2017-01-18 13:17 UTC, asr commented on Setup.hs
> +{-# OPTIONS_GHC -fno-warn-deprecations #-}
> Please create a MVE a file an GHC issue.

CC'ing to me. My GHC Trac user is asr.

2017-01-18 13:18 UTC, asr commented
The test-suite continues failing...

2017-01-18 13:38 UTC, asr requested changes

2017-01-18 13:38 UTC, asr commented on Setup.hs
> +
Please add `-Wall` and fix the warnings.

2017-01-18 13:40 UTC, asr requested changes
The test-suite continues failing...

2017-01-18 16:06 UTC, jonaprieto commented
Where can I find `shelltest` binaries? I couldn't find it to install in OSX.

2017-01-18 19:46 UTC, asr approved these changes

2017-01-18 19:49 UTC, merged

2017-01-18 19:50 UTC, asr commented
@jonaprieto, I squashed the commits and added some information from the OP.

Please delete the branch.

Thanks!